apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Namespace }}
data:
  EUREKA_SERVER: {{ .Values.secrets.eurekaServer | b64enc | quote }}
  KAFKA_SASL_USERNAME: {{ .Values.secrets.kafkaSaslUsername | b64enc | quote }}
  KAFKA_SASL_PASSWORD: {{ .Values.secrets.kafkaSaslPassword | b64enc | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.secrets.kafkaBootstrapServers | b64enc | quote }}
  JWK_SET_URI: {{ .Values.secrets.jwkSetUri | b64enc | quote }}
  CORS_ORIGINS: {{ .Values.secrets.corsOrigins | b64enc | quote }}
  DB_HOST: {{ .Values.secrets.dbHost }}
  DB_PORT: {{ .Values.secrets.dbPort }}
  DB_NAME: {{ .Values.secrets.dbName }}
  DB_USERNAME: {{ .Values.secrets.dbUsername }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}