version: "3"
services:
  postgres:
    image: postgis/postgis:15-3.5
    container_name: ecco-ride-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eco-ride
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
      MONGO_INITDB_DATABASE: electric_stations
    ports:
      - "27017:27017"
    restart: unless-stopped

  kafka:
    container_name: kafka
    image: "bitnami/kafka:latest"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - 9094:9094

  redpanda-console:
    container_name: redpanda-kanban
    image: redpandadata/redpanda:v24.3.14
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - 8084:8080
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:9092"]
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"

  auth-service:
    container_name: auth-service
    build: ./auth-service
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"

  chat-service:
    container_name: chat-service
    build: ./chat-service
    depends_on:
      - mongo
      - kafka
    ports:
      - "8080:8082"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MONGO_DB_URI: mongodb://mongo:27017/chat-db
      JWK_SET_URI: http://auth-service:3000
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"

  notification-service:
    container_name: notification-service
    build: ./notification-service
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_HOST: postgres
      DB_PORT: 5432
      DB_Name: notification
      JWK_SET_URI: http://auth-service:3000
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
