version: "3"
services:
  postgres:
    image: postgis/postgis:15-3.5
    container_name: ecco-ride-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eco-ride
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
      MONGO_INITDB_DATABASE: electric_stations
    ports:
      - "27017:27017"
    restart: unless-stopped
