apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-backup-pvc
  namespace: mysql
spec:
  #storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: mysql
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: mysql:8.0
              command:
                - /bin/bash
                - -c
                - |
                  #!/bin/bash

                  backup_db() {
                    DB_NAME=$1
                    BACKUP_DIR="/backup"
                    DATE=$(date +%Y%m%d%H%M%S)
                    BACKUP_FILE="$BACKUP_DIR/$DB_NAME-$DATE.sql"

                    mysqldump -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME > $BACKUP_FILE

                    if [ $? -eq 0 ]; then
                      echo "Backup of $DB_NAME created successfully at $BACKUP_FILE"
                    else
                      echo "Error creating backup of $DB_NAME"
                      exit 1
                    fi
                  }

                  DB_HOST="mysql.mysql.svc.cluster.local"
                  DB_USER="root"
                  DB_PASSWORD="secretpassword"

                  backup_db "kanban"
                  backup_db "notification"
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: mysql-backup-pvc
