apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod #buypass-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory #https://api.buypass.com/acme/directory
    email: {{ .Values.letsEncryptClusterIssuer.email }}
    privateKeySecretRef:
      name: buypass-prod #letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

