repositories:
  - name: strimzi
    url: https://strimzi.io/charts/

releases:
- name: strimzi
  namespace: kafka
  chart: strimzi/strimzi-kafka-operator
  installed: true
  values:
    - values.yaml
 