version: "3"
services:
  postgres:
    image: postgis/postgis:15-3.5
    container_name: ecco-ride-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eco-ride
    ports:
      - "5432:5432"
