version: "3"
services:
  postgres:
    image: postgis/postgis:15-3.5
    container_name: ecco-ride-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eco-ride
    ports:
      - "5432:5432"

  app:
    image: walymb/ride-service:0.0.1
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: eco-ride
      DB_SSLMODE: disable
      JWKS_URL: http://192.168.100.130:3000/auth/.well-known/jwks.json
    ports:
      - "8080:8080"
