apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-chat-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  EUREKA_SERVER: {{ .Values.secrets.eurekaServer | b64enc }}
  KAFKA_SASL_USERNAME: {{ .Values.secrets.kafkaSaslUsername | b64enc }}
  KAFKA_SASL_PASSWORD: {{ .Values.secrets.kafkaSaslPassword | b64enc }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.secrets.kafkaBootstrapServers | b64enc }}
  JWK_SET_URI: {{ .Values.secrets.jwkSetUri | b64enc }}
  CORS_ORIGINS: {{ .Values.secrets.corsOrigins | b64enc }}
  MONGO_DB_URI: {{ .Values.secrets.mongoDbUri | b64enc }}