apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ride-secrets
  namespace: {{ .Release.Namespace }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.secrets.kafkaBootstrapServers | b64enc | quote }}
  JWKS_URL: {{ .Values.secrets.jwkSetUri | b64enc | quote }}
  CORS_ORIGINS: {{ .Values.secrets.corsOrigins | b64enc | quote }}
  DATABASE_URL: {{ .Values.secrets.dbUrl | b64enc | quote }}
