apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc }}
  JWT_EXPIRES_IN: {{ .Values.secrets.jwtExpiresIn | b64enc }}
  PUBLIC_KEY_PATH: {{ .Values.secrets.publicKeyPath | b64enc }}
  PRIVATE_KEY_PATH: {{ .Values.secrets.privateKeyPath | b64enc }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | b64enc }}
  GOOGLE_CALLBACK_URL: {{ .Values.secrets.googleCallbackUrl | b64enc }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.githubClientId | b64enc }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | b64enc }}
  GITHUB_CALLBACK_URL: {{ .Values.secrets.githubCallbackUrl | b64enc }}
  AWS_REGION: {{ .Values.secrets.awsRegion | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | b64enc }}
  AWS_S3_BUCKET: {{ .Values.secrets.awsS3Bucket | b64enc }}
  JWT_KID: {{ .Values.secrets.jwtKid | b64enc }}